# Generated by Django 2.1.4 on 2019-03-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, '申请'), (2, '通过'), (0, '拒绝')], default=1, verbose_name='审核状态'),
        ),
    ]
