# Generated by Django 2.1.3 on 2019-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, '申请'), (2, '通过'), (0, '拒绝')], default=1, verbose_name='审核状态'),
        ),
    ]
