# Generated by Django 2.1.3 on 2019-03-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190304_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='NO')),
                ('kemu', models.CharField(max_length=128, verbose_name='科目')),
                ('score', models.IntegerField(verbose_name='成绩')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student2', verbose_name='ID')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
            },
        ),
    ]
