# Generated by Django 2.1.3 on 2019-03-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='NO'),
        ),
    ]
